
project_id = "ufdcvxmizlzlnyyqpfck"

[functions.orbit-gemini-analysis]
verify_jwt = true

[functions.process-image-batch]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.download-processed-images]
verify_jwt = true

[functions.upload-order-images]
verify_jwt = true

[functions.get-thumbnails]
verify_jwt = true

[functions.send-order-completion-email]
verify_jwt = true

[functions.upload-order-images-direct]
verify_jwt = true

[functions.debug-order-lookup]
verify_jwt = true

[functions.verify-payment-order]
verify_jwt = true
